"""empty message

Revision ID: bfad2980b921
Revises: 
Create Date: 2021-03-30 04:21:20.482761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfad2980b921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('loan_name', sa.String(), nullable=False),
    sa.Column('rpay', sa.String(), nullable=False),
    sa.Column('rate_type', sa.String(), nullable=False),
    sa.Column('rate_min', sa.Float(), nullable=True),
    sa.Column('rate_max', sa.Float(), nullable=True),
    sa.Column('rate_avg', sa.Float(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.loan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation')
    op.drop_table('loan')
    # ### end Alembic commands ###
